-- LekhaSignal Snowflake deployment blueprint. Run with ACCOUNTADMIN only for initial setup.
CREATE OR REPLACE ROLE LEKHASIGNAL_PLATFORM_ADMIN;
CREATE OR REPLACE ROLE LEKHASIGNAL_TRANSFORMER;
CREATE OR REPLACE ROLE LEKHASIGNAL_ANALYST;
CREATE OR REPLACE WAREHOUSE LEKHASIGNAL_INGEST_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE OR REPLACE WAREHOUSE LEKHASIGNAL_TRANSFORM_WH WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE OR REPLACE RESOURCE MONITOR LEKHASIGNAL_DAILY_CREDITS WITH CREDIT_QUOTA = 50 FREQUENCY = DAILY START_TIMESTAMP = IMMEDIATELY TRIGGERS ON 75 PERCENT DO NOTIFY ON 90 PERCENT DO SUSPEND;
ALTER WAREHOUSE LEKHASIGNAL_TRANSFORM_WH SET RESOURCE_MONITOR = LEKHASIGNAL_DAILY_CREDITS;
CREATE OR REPLACE DATABASE LEKHASIGNAL;
CREATE OR REPLACE SCHEMA LEKHASIGNAL.RAW;
CREATE OR REPLACE SCHEMA LEKHASIGNAL.CORE;
CREATE OR REPLACE SCHEMA LEKHASIGNAL.MART;
CREATE OR REPLACE SCHEMA LEKHASIGNAL.CONTROL;

CREATE OR REPLACE TABLE LEKHASIGNAL.RAW.PAYMENT_EVENTS (
  event_id STRING, payment_id STRING, invoice_id STRING, customer_id STRING,
  amount NUMBER(18,2), currency STRING, event_ts TIMESTAMP_TZ, source_lsn NUMBER,
  payload VARIANT, ingest_ts TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE LEKHASIGNAL.RAW.INVOICE_EVENTS (
  event_id STRING, invoice_id STRING, customer_id STRING, invoice_status STRING,
  invoice_total NUMBER(18,2), issued_at TIMESTAMP_TZ, source_lsn NUMBER,
  payload VARIANT, ingest_ts TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);

-- Replace this external stage with a least-privilege GCS storage integration in a live account.
-- CREATE STAGE LEKHASIGNAL.RAW.GCS_BILLING_STAGE STORAGE_INTEGRATION = ... URL = 'gcs://...';
-- CREATE PIPE LEKHASIGNAL.RAW.PAYMENT_PIPE AUTO_INGEST=TRUE AS COPY INTO LEKHASIGNAL.RAW.PAYMENT_EVENTS FROM @LEKHASIGNAL.RAW.GCS_BILLING_STAGE;

CREATE OR REPLACE MASKING POLICY LEKHASIGNAL.CONTROL.EMAIL_MASK AS (value STRING) RETURNS STRING ->
  CASE WHEN CURRENT_ROLE() IN ('LEKHASIGNAL_PLATFORM_ADMIN','LEKHASIGNAL_ANALYST') THEN value ELSE '***masked***' END;

GRANT USAGE ON DATABASE LEKHASIGNAL TO ROLE LEKHASIGNAL_TRANSFORMER, LEKHASIGNAL_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LEKHASIGNAL TO ROLE LEKHASIGNAL_TRANSFORMER, LEKHASIGNAL_ANALYST;
GRANT SELECT ON FUTURE TABLES IN DATABASE LEKHASIGNAL TO ROLE LEKHASIGNAL_ANALYST;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE LEKHASIGNAL TO ROLE LEKHASIGNAL_TRANSFORMER;
